# This is a basic workflow to help you get started with Actions

name: CI (FHIR Validation)

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'input/**'
      - '.github/workflows/**'
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      SIMPLIFIER_USERNAME:
        required: true
      SIMPLIFIER_PASSWORD:
        required: true
      WORKFLOW_PERMISSION_GITHUB:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: write
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Validate all resources using Firely Terminal
  CI_FHIR_VALIDATION:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code (PR)
        uses: actions/checkout@v5
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Checkout code (Main)
        uses: actions/checkout@v5
        if: github.event_name != 'pull_request'

#      # can be deleted after https://github.com/hapifhir/org.hl7.fhir.core/pull/1990 is merged (adding json5 support)
#      - name: Strip pure comment lines
#        run: |
#          # nur Zeilen löschen, die mit optionalem Whitespace und dann // anfangen
#          sed -i '/^[[:space:]]*\/\//d' validator/advisor.json
#          # leere Zeilen aufräumen
#          sed -i '/^[[:space:]]*$/d' validator/advisor.json
#          cat validator/advisor.json

      - name: Firely.Terminal (GitHub Actions)
        uses: FirelyTeam/firely-terminal-pipeline@v0.7.8
        with:
          PATH_TO_CONFORMANCE_RESOURCES: fsh-generated/resources/
          DOTNET_VALIDATION_ENABLED: false
          JAVA_VALIDATION_ENABLED: true
          JAVA_VALIDATION_OPTIONS: >
            -allow-example-urls true
            -output validation.json
            -html-output validation.html
            -show-message-ids
            -language de
            -jurisdiction de
            -display-issues-are-warnings
            -resolution-context file:fsh-generated/resources/
            -advisor-file validator/advisor.json
          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
          SUSHI_ENABLED: true
          SUSHI_OPTIONS: .
          EXPECTED_FAILS: VALIDATION_CONFORMANCE_JAVA VALIDATION_CONFORMANCE_DOTNET

      - name: Upload validation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fhir-validation-results
          path: |
            validation.json
            validation.html
          retention-days: 1

      - name: Convert Validation Report
        uses: patrick-werner/validation-outcome-markdown-renderer@v1
        continue-on-error: true
        with:
          bundle-file: validation.json
          include: warnings
          filters: |
#            fileName|messageId|detailsWildcard|location

      - name: Validate Resource Status
        uses: patrick-werner/fhir-resource-status-check@1.2.0
        with:
          folder: './Resources/fsh-generated/resources/'

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions Bot
          committer_email: ActionBot@github.com
          add: fsh-generated/resources/
          message: auto-generated FHIR files by GitHub Actions (CI FSH to FHIR Validation)
